In [1]:
import numpy as np, random, operator, pandas as pd, math

class Direction:
    def __init__(self, input_size, hidden_size, output_size):
        self.w1 = np.random.uniform(-1., 1., (input_size,hidden_size))
        self.w2 = np.random.uniform(-1., 1., (hidden_size,hidden_size))
        self.w3 = np.random.uniform(-1., 1., (hidden_size,output_size))
        
    def __repr__(self):
        return str(self.w1) + ',' + str(self.w2) + ',' + str(self.w3)
    
    #def __getitem__(self, key):
        #return getattr(self, key)
        #return self[key]
        
    def getWeights(self):
        return self.w1, self.w2, self.w3
    
class Fitness:
    def __init__(self, path):
        
        print('path', path)
        
        self.w1 = path.w1
        self.w2 = path.w2
        self.w3 = path.w3
        self.bias = 1
        self.layer1 = []
        self.layer2 = []
        
        self.distance = 0
        self.fitness = 0
        
        
    def sigmoid(self, x, derivative=False):
        return x*(1.0-x) if derivative else 1.0/(1.0+np.exp(-x))
    
    # calcular a ação a ser executada seguindo a maior probabilidade
    def feedforward(self, input=None):
        input_array = []

        if input is None:
            input_array = np.array(self.input, ndmin=2)
        else:
            input_array = np.array(input, ndmin=2)
        
        #xxx = np.dot(input_array, self.w1)
            
        self.layer1 = self.sigmoid(np.dot(input_array, self.w1) + self.bias)
        self.layer2 = self.sigmoid(np.dot(self.layer1, self.w2) + self.bias)
        self.output = self.sigmoid(np.dot(self.layer2, self.w3) + self.bias)
        
    def calDistance(self):
        
        #print('calcdistance', self)
        
        square.centerx, square.centery = WIDTH // 2, HEIGHT // 2
        
        collided = False
        
        while collided == False:
            
            distance_up = distance_down = distance_right = distance_left = 0
        
            for wall in walls:
                x1, x2 = square.centerx, square.centery
                y1, y2 = wall.centerx, wall.centery
                
                if wall.centerx == square.centerx:
                    if square.centery < wall.centery:
                        distance_up = math.hypot(x1-x2, y1-y2)
                        
                    if square.centery > wall.centery:
                        distance_down = math.hypot(x1-x2, y1-y2)
                        
                if wall.centery == square.centery:
                    if square.centerx < wall.centerx:
                        distance_right = math.hypot(x1-x2, y1-y2)
                        
                    if square.centerx > wall.centerx:
                        distance_left = math.hypot(x1-x2, y1-y2)
                    
            input_array = distance_right, distance_down, distance_left, distance_up
        
            self.feedforward(input_array)
        
            action = np.argmax(self.output)
            
            #print('action', action)

            screen.fill(BLACK)  

            dt = clock.tick(60)
            
            #0 direita
            #1 baixo
            #2 esquerda
            #3 cima
            
            if (action == 0):
                pos_x = velocity * dt
                square.move_ip(pos_x, 0)

            if (action == 1):
                pos_y = (velocity * dt)
                square.move_ip(0, pos_y)

            if (action == 2):
                pos_x = -(velocity * dt)
                square.move_ip(pos_x, 0)
                
            if (action == 3):
                pos_y = -(velocity * dt)
                square.move_ip(0, pos_y)

            for wall in walls:
                if square.colliderect(wall):
                    print('bateu')
                    collided = True

            if (collided == True):
                break;
            
            for wall in walls:
                pygame.draw.rect(screen, WHITE, wall)
                
            pygame.draw.rect(screen, GREEN, exit)

            pygame.draw.rect(screen, RED, square)
            
            
            #init_x, init_y = WIDTH // 2, HEIGHT // 2
            init_x, init_y = exit.centerx, exit.centery
            current_x, current_y = square.centerx, square.centery
                
            xDis = abs(current_x - init_x)
            #calcula a distancia dos eixos y
            yDis = abs(current_y - init_y)
            #eleva as diferenças ao quadrado, soma e calcula a raiz
            self.distance = np.sqrt((xDis ** 2) + (yDis ** 2))
            
            str_mov = 'distance = ' + str(round(self.distance, 2))
            text_mov = font.render(str_mov, True, WHITE)
            text_rect = text_mov.get_rect()
            text_rect.center = (WIDTH // 2, HEIGHT - 60)

            screen.blit(text_mov, text_rect)
            
            pygame.display.flip()

        return self.distance
        
    def getPathFitness(self):
        if (self.fitness == 0):
            distance = int(self.calDistance())
            if (distance > 0):
                self.fitness = 1 / distance
            self.fitness = 1
        return self.fitness

    def getDistance(self):
        return self.distance



import pygame
import sys

BLACK = pygame.Color(0, 0, 0)
WHITE = pygame.Color(255, 255, 255)
RED = pygame.Color(255, 0, 0)
GREEN = pygame.Color(0, 255, 0)
WIDTH, HEIGHT = 600, 300

SQUARE_WIDTH, SQUARE_HEIGHT = 5, 5
WALL_WIDTH, WALL_HEIGHT = 20, 20

velocity = 0.1

pygame.init()

screen = pygame.display.set_mode((WIDTH, HEIGHT))

clock = pygame.time.Clock()

square = pygame.Rect(WIDTH // 2, HEIGHT // 2, SQUARE_WIDTH, SQUARE_HEIGHT)


levels = [
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
    "W           W E W            W",
    "W      WWWWWW   W            W",
    "W      W    W   W            W",
    "W      W    W   W            W",
    "W      W    W   W            W",
    "W      W        W            W",
    "W      W        W            W",
    "W      W    W   W            W",
    "W      W    W   W            W",
    "W      W    W   W            W",
    "W      W    W                W",
    "W      W    W                W",
    "W           W   W            W",
    "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"
]


left = 0
top = 0

walls = []
exit = 0

for row in levels:
    for col in row:
        if col == 'W':
            wall = pygame.Rect(left, top, WALL_WIDTH, WALL_HEIGHT)
            walls.append(wall)
        if col == 'E':
            exit = pygame.Rect(left, top, WALL_WIDTH, WALL_HEIGHT)
        left += WALL_WIDTH
    top += WALL_HEIGHT
    if left >= WIDTH:
        left = 0


font = pygame.font.Font('freesansbold.ttf', 12)
        
class GeneticAlgorithm:
    def __init__(self, population, populationSize, eliteSize, mutationRate, generations):
        self.population = population
        self.populationSize = populationSize
        self.eliteSize = eliteSize
        self.mutationRate = mutationRate
        self.generations = generations
        self.currentPopulation = []
        self.bestFitnessMovimentations = 1
        self.bestDistance = 0

    def start(self):
        #self.currentPopulation = self.initialPopulation(self.populationSize, self.population)
        self.currentPopulation = self.population

        for i in range(0, self.generations):
            print('generation: ', i)
            self.currentPopulation = self.nextGeneration(self.currentPopulation, self.eliteSize, self.mutationRate)

        bestIndividualIndex = self.rankIndividuals(self.currentPopulation)[0][0]
        bestIndividual = self.currentPopulation[bestIndividualIndex]
        print(bestIndividual)
        
        
    def createPath(self, listDirections):
        return random.sample(listDirections, len(listDirections))


    def initialPopulation(self, populationSize, listDirections):
        population = []

        for i in range(0, populationSize):
            population.append(self.createPath(listDirections))
        return population


    def rankIndividuals(self, population):
        fitnessResults = {}
        
        for i in range(0, len(population)):
            #print('population', population[i])
            fitnessResults[i] = Fitness(population[i]).getPathFitness()
            
        return sorted(fitnessResults.items(), key = operator.itemgetter(1), reverse = False)


    def selection(self, populationRanked, eliteSize):
        #print('populationRanked', populationRanked)

        selectionResults = []
        df = pd.DataFrame(np.array(populationRanked), columns=["Index", "Fitness"])
        df['cum_sum'] = df.Fitness.cumsum()
        df['cum_perc'] = 100 * df.cum_sum / df.Fitness.sum()

        for i in range(0, eliteSize):
            selectionResults.append(populationRanked[i][0])

        for i in range(0, len(populationRanked) - eliteSize):
            pick = 100 * random.random()

            for i in range(0, len(populationRanked)):
                if pick <= df.iat[i, 3]:
                    selectionResults.append(populationRanked[i][0])
                    break
        return selectionResults

    def matingPool(self, population, selectionResults):
        matingpool = []

        for i in range(0, len(selectionResults)):
            index = selectionResults[i]
            matingpool.append(population[index])
        return matingpool

    def breed(self, parent1, parent2):
        child = []
        childP1 = []
        childP2 = []
        weights = []
        
        
        # a reproducao vai ser diferente
        
        for i in np.arange(3):
            print('i', i)
            # pega os pesos do parent1
            weightsParent1 = parent1.getWeights()[i]
            weightsParent2 = parent2.getWeights()[i]
            
        
            nodesA = int(random.random() * len(weightsParent1))
            nodesB = int(random.random() * len(weightsParent2))

            startNode = min(nodesA, nodesB)
            endNode = max(nodesA, nodesB)

            for j in range(startNode, endNode):
                weights.append(weightsParent1[j])
                
            childP1.append(weights)
            
            childP2.append([item for item in weightsParent2 if item not in childP1[i]])

        child = childP1 + childP2

        return child

    def breedPopulation(self, matingpool, eliteSize):
        children = []
        length = len(matingpool) - eliteSize
        pool = random.sample(matingpool, len(matingpool))

        for i in range(0, eliteSize):
            children.append(matingpool[i])

        for i in range(0, length):
            parent1 = pool[i]
            parent2 = pool[len(matingpool)-i-1]
            child = self.breed(parent1, parent2)
            children.append(child)

        return children


    def mutate(self, individual, mutationRate):
        for weight in range(len(individual)):
            for neuron in range(len(weight)):
                if (random.random() < mutationRate):
                    newWeight = random.uniform(-1., 1)
                    individual[weight][neuro] = newWeight

        return individual

    def mutatePopulation(self, population, mutationRate):
        mutatedPopulation = []

        for individual in range(0, len(population)):

            mutatedIndividual = self.mutate(population[individual], mutationRate)
            mutatedPopulation.append(mutatedIndividual)

        return mutatedPopulation

    def nextGeneration(self, currentGeneration, eliteSize, mutationRate):
        populationRanked = self.rankIndividuals(currentGeneration)
        selectionResults = self.selection(populationRanked, eliteSize)
        matingpool = self.matingPool(currentGeneration, selectionResults)
        children = self.breedPopulation(matingpool, eliteSize)
        return self.mutatePopulation(children, mutationRate) 


while True:

    events = pygame.event.get()
    
    for event in events:
        if event.type == pygame.KEYUP:
            if event.key == pygame.K_SPACE:
                listDirections = []

                for i in range(0, 5):
                    listDirections.append(Direction(4, 2, 4))
                    
                #print(listDirections)
                    
                ga = GeneticAlgorithm(population=listDirections, populationSize=5, eliteSize=2, mutationRate=0.01, generations=5)
                ga.start()


pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
generation:  0
path [[ 0.61965357 -0.02342715]
 [ 0.11055765  0.99026849]
 [-0.0953099  -0.15710424]
 [ 0.2299333  -0.51053713]],[[ 0.03638929  0.96451653]
 [-0.67517102  0.30529296]],[[ 0.82295581  0.89466489  0.97136647  0.09812879]
 [-0.28647743 -0.61499876 -0.91213942  0.27648145]]
bateu
path [[-0.62812215  0.94583918]
 [-0.50382961  0.15928014]
 [-0.55832345  0.09243243]
 [ 0.56736923 -0.321527  ]],[[ 0.77059889 -0.79564633]
 [-0.51626803 -0.7356862 ]],[[ 0.03085471  0.51822809  0.80895217  0.3696526 ]
 [ 0.75067417 -0.45523761 -0.56266368 -0.66122389]]
bateu
path [[ 0.21968235  0.12537714]
 [ 0.46453883 -0.14403057]
 [-0.6969683  -0.73549277]
 [-0.09219817  0.22607743]],[[ 0.47232862 -0.20495402]
 [-0.58945505  0.34436346]],[[ 0.64285282 -0.0271675  -0.57225369 -0.50524087]
 [-0.84077697 -0.33144725  0.91688603  0.06238181]]
bateu
path [[-0.96706717  0.78458448]
 [-0.94457623 -0.3633526 ]
 [ 0.53

/home/joeltonguerreiro/workspace/python/env3/lib/python3.7/site-packages/ipykernel_launcher.py:36: RuntimeWarning: overflow encountered in exp


bateu
path [[ 0.15695242 -0.14545915]
 [-0.93247406 -0.3350061 ]
 [ 0.58442787  0.62269353]
 [-0.3595159  -0.70158351]],[[ 0.74105061 -0.96520667]
 [ 0.30175399 -0.55681619]],[[ 0.99431343 -0.28816157 -0.81294605  0.89619101]
 [ 0.79080494 -0.49105573 -0.73017986 -0.79479376]]
bateu
i 0


AttributeError: 'generator' object has no attribute 'all'